# 2. 커스텀 에러와 에러 확장
개발을 하다 보면 자체 에러 클래스가 필요한 경우가 종종 생긴다.

직접 에러 클래스를 만든 경우, 이 에러들은 `message`이나 `name`, 가능하다면 `stack` 프로퍼티를 지원해야 한다. 물론 이런 프로퍼티 이외에도 다른 프로퍼티를 지원할 수 있다.

앞서 배운 바와 같이 `throw`의 인수에는 아무런 제약이 없기 때문에 커스텀 에러 클래스는 반드시 `Error`를 상속할 필요가 없다. 그렇지만 `Error`를 상속받아 커스텀 에러 클래스를 만들게 되면 `obj instanceof Error`를 사용해서 에러 객체를 식별할 수 있다는 장점이 있다.

## 에러 확장하기
`Error`을 상속받은 커스텀 에러 클래스 `ValidationError`을 구현해 보았다.
```js
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

function test() {
  throw new ValidationError('에러 발생');
}

try {
  test();
} catch(err) {
  alert(err.message); // 에러 발생
  alert(err.name); // ValidationError
  alert(err.stack); // 각 행 번호가 있는 중첩된 호출들의 목록
}
```
부모 생성자를 호출하고 있다는 것을 주목해야 한다. 자바스크립트에서는 자식 생성자 안에서 `super`를 반드시 호출해야 한다. `message` 프로퍼티는 부모 생성자에서 설정된다.

부모 생성자에서 `message`뿐만 아니라 `name` 프로퍼티도 설정(`Error`)하기 때문에, 원하는 값으로 재설정해주었다.

`ValidationError`의 사용법은 다음과 같다.
```js
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new ValidationError('No field: age');
  }
  if (!user.name) {
    throw new ValidationError('No field: name');
  }

  return user;
}

// try..catch와 readUser를 함께 사용한 예시이다.
try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No field: name
  } else if (err instanceof SyntaxError) { // JSON.parse에서 발생하는 에러를 처리한다.
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기한다.
  }
}
```
이제 `try..catch` 블록에서 커스텀 에러 `ValidationError`와 `JSON.parse`에서 발생하는 `SyntaxError` 둘 다를 처리할 수 있게 되었다.

이 과정에서 `instanceof`로 에러 유형을 확인했다. 에러 유형 확인은 `err.name`으로도 가능하지만 확장성을 위해 `instanceof`을 사용하는 것을 추천한다.

## 더 깊게 상속하기
앞서 만든 `ValidationError` 클래스는 너무 포괄적이다. 필수 프로퍼티가 없는 경우에 대응할 수 있도록 좀 더 구체적인 클래스 `PropertyRequiredError`를 만들어 보겠다. `PropertyRequiredError`에는 누락된 프로퍼티에 대한 추가 정보가 담겨야 한다.
```js
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super('No property: ' + property);
    this.name = 'PropertyRequiredError';
    this.property = property;
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new PropertyRequiredError('age');
  }
  if (!user.name) {
    throw new PropertyRequiredError('name');
  }

  return user;
}

// try..catch와 readUser를 함께 사용하면 다음과 같다.
try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert('Invalid data: ' + err.message); // Invalid data: No property: name
    alert(err.name); // PropertyRequiredError
    alert(err.property); // name
  } else if (err instanceof SyntaxError) {
    alert('JSON Syntax Error: ' + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기한다.
  }
}
```
새롭게 만든 클래스 `PropertyRequiredError`는 사용하기 쉽다. `new PropertyRequiredError(property)`처럼 프로퍼티 이름을 전달하기만 하면 된다. 사람이 읽을 수 있는 `message`는 생성자가 알아서 만들어준다.

여기서 주목할 점은 `PropertyRequiredError` 생성자 안에서 `this.name`을 수동으로 할당해 주었다는 것이다. 그런데 이렇게 매번 커스텀 에러 클래스의 생성자 안에서 `this.name`를 할당해 주는 것은 번거로운 작업이다. 이런 번거로운 작업은 ‘기본 에러’ 클래스를 만들고 커스텀 에러들이 이 클래스를 상속받게 하면 피할 수 있다. 기본 에러의 생성자에 `this.name = this.constructor.name`를 추가하면 된다.

기본 에러 클래스를 `MyError`라고 부르겠다.

`MyError`를 사용하면 다음과 같이 커스텀 에러 클래스를 간결하게 할 수 있다.
```js
class MyError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}

class ValidationError extends MyError { /*...*/ }

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super('No property: ' + property);
    this.property = property;
  }
}

// 제대로 된 이름이 출력된다.
alert(new PropertyRequiredError('field').name); // PropertyRequiredError
```

## 예외 감싸기
현재 `readUser`에 대한 에러 처리 스키마는 다음과 같다.
```js
try {
  ...
  readUser()  // 잠재적 에러 발생처
  ...
} catch (err) {
  if (err instanceof ValidationError) {
    // validation 에러 처리
  } else if (err instanceof SyntaxError) {
    // 문법 에러 처리
  } else {
    throw err; // 알 수 없는 에러는 다시 던지기한다.
  }
}
```
위 스키마에는 두 종류의 에러만 나와 있다. 그런데 에러의 종류는 더 추가될 수 있다. 에러 종류가 많아지면 그때마다 에러 처리 분기문을 추가해야 하나라는 의문이 생길 수 있다.

보통은 그렇지 않다. 실제 우리가 필요로 하는 정보는 ‘데이터를 읽을 때’ 에러가 발생했는지에 대한 여부이다. 왜 에러가 발생했는지와 자세한 설명은 대부분의 경우 필요하지 않다. 필요할 때 에러 세부사항에 대한 정보를 얻을 수 있는 방법이 있다면 물론 더 좋을 것이다.

이런 에러 처리 기술은 <strong>예외 감싸기(wrapping exception)</strong>라고 부른다. 예외 감싸기는 다음과 같은 순서로 진행된다.
1.  '데이터 읽기’와 같은 포괄적인 에러를 대변하는 새로운 클래스  `ReadError`를 만든다.
2.  함수  `readUser`  발생한  `ValidationError`,  `SyntaxError`  등의 에러는  `readUser`  내부에서 잡고 이때  `ReadError`를 생성한다.
3.  `ReadError`  객체의  `cause`  프로퍼티에는 실제 에러에 대한 참조가 저장된다.

이렇게 예외 감싸기 기술을 써 스키마를 변경하면 `readUser`를 호출하는 코드에서는 `ReadError`만 확인하면 된다. 데이터를 읽을 때 발생하는 에러 종류 전체를 확인하지 않아도 된다. 추가 정보가 필요한 경우엔 `cause` 프로퍼티를 확인하면 된다.
```js run
class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { /*...*/ }
class PropertyRequiredError extends ValidationError { /* ... */ }

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError('age');
  }

  if (!user.name) {
    throw new PropertyRequiredError('name');
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError('Syntax Error', err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError('Validation Error', err);
    } else {
      throw err;
    }
  }

}

try {
  readUser('{잘못된 형식의 json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert('Original error: ' + e.cause);
  } else {
    throw e;
  }
}
```
Syntax 에러나 Validation 에러가 발생한 경우 해당 에러 자체를 다시 던지기 하지 않고 `ReadError`를 던지게 됩니다.

이렇게 되면,  `readUser`를 호출하는 바깥 코드에서는  `instanceof ReadError`  하나만 확인하면 된다. 에러 처리 분기문을 여러 개 만들 필요가 없어진다.

'예외 감싸기’란 이름은 종류별 에러를 좀 더 추상적인 에러,  `ReadError`에 하나로 모아(wrap) 처리하기 때문에 붙여졌다. 이런 기법은 객체 지향 프로그래밍에서 널리 쓰이는 패턴이다.

## 요약
-   커스텀 클래스는  `Error`나 다른 내장 에러 클래스를 상속받아 만들 수 있다. 이때  `super`를 호출해야 하며  `name`  프로퍼티를 신경 써야 한다.
-   `instanceof`를 사용하면 에러 종류를 판별할 수 있다. 그런데 서드파티 라이브러리에서 온 에러 객체는 클래스를 알아내는 것이 쉽지 않다. 이때는  `name`  프로퍼티를 사용해 오류 종류를 확인할 수 있다.
-   예외 감싸기는 널리 알려진 예외 처리 기술이다. 예외 감싸기를 적용한 함수에서는 모든 에러를 종류별로 처리하지 않는다. 대신 모든 에러를 포함할 수 있는 추상 에러를 하나 만들고, 에러가 발생하면 이 추상 에러를 던진다. 추상 에러를 던질 때 실제 발생한 에러를 추상 에러의 프로퍼티(`err.cause`)로 넘기면 구체적인 에러 정보를 함께 넘겨줄 수 있다.
